### PR TITLE
`calculateLD.R`: Fixed incorrect SNP map

### LINKED ISSUE #177: `LDpred2`: Error when using LD-data produced by `calculatedLD.R`
**Describe the bug**
Using LD-data by `calculateLD.R` (1.5M SNPs, 10K individuals) leads to the following error in `ldpred2.R`
image

**To Reproduce**
1. Run `calculateLD.R` with `--sample-individuals` and `--extract`
2. Run `ldpred2.R` with the outputted LD-files

### LINKED ISSUE #227: A small bug : na.rm is missing : quantile (na.rm = T, ...)
https://github.com/comorment/containers/blob/c5770959620ac7a658d640ade3b1384041fdc803/scripts/pgs/LDpred2/ldpred2.R#L314

### PR DESCRIPTION
**Pull request by deepchocolate**
Fixes #177 
Fixes #227 

Changes proposed in this pull request:

- Filter genotype map by SNP RSIDs in `calculateLD.R`
- Moved testing of LD estimation and analysis to a script of their own: `tests/test_LDpred2/scripts/ld.sh`
- Added test of `ldpred2.R` using LD data filtered by `--extract` (SNPs) and `--sample-individuals` 
- Added script to create blocks in LD matrixes: `splitLD.R`
- Added script to analyze and plot LD: `analyzeLD.R`: Example plot:

image

Plotting functionality modified from: https://github.com/privefl/bigsnpr/issues/4

## Before submitting

- [x] I've read and followed all steps in the [Making a pull request](https://github.com/comorment/containers/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [x] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/comorment/containers/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [x] If this PR fixes a bug, I've added a test that will fail without my fix.
- [x] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.

### CODE REVIEW

**Comment by espenhgn** [comment]
The "Greetings" action failure is outside our control and can be ignored: https://github.com/actions/first-interaction/issues/286

**Review by espenhgn — APPROVED** [review]
Thanks @deepchocolate. Looks good to me, only bumped the version file + a couple minor fixes. The LD unittests failed on my end however, because of wrong file path(s). I've pushed a couple of fixes hardcoding the `/ldpred2_ref` mount point in calls pointing to these datas.

**Comment by espenhgn** [comment]
> > Thanks @deepchocolate. Looks good to me, only bumped the version file + a couple minor fixes. The LD unittests failed on my end however, because of wrong file path(s). I've pushed a couple of fixes hardcoding the `/ldpred2_ref` mount point in calls pointing to these datas.
> 
> Great, thanks for the review! I planned to do a test run on real data prior to merging, but haven't been able to login to TSD since Friday, so leaving it hanging here until that.

Perhaps good to run a test in MoBA or similar. But can confirm, TSD p697 rhel login machines are unreachable. But you can use Windows VM -> Putty -> p697-appnode-norment01 to get access to the resource.

File: scripts/pgs/LDpred2/fun.R [hunk 1]
```diff
@@ -161,3 +161,47 @@ rename_columns <- function(df, old_names, new_names) {
...
+  if (verbose) cat('Retained', nrow(dta), 'out of', nKept, 'rows\n')
+  dta
+}
+
+# Get the betas from snp_ldpred2_auto
+#' @param fitAuto The return value form snp_ldpred2_auto
+#' @param quantile Range of estimates to keep
+getBetasAuto <- function (fitAuto, quantile=0.95, verbose=T) {
+  range <- sapply(fitAuto, function (auto) diff(range(auto$corr_est)))
+  # Keep chains that pass the filtering below
```
Comment (deepchocolate) [inline scripts/pgs/LDpred2/fun.R:200]: @espenhgn I noted that the problem om missing values start here (l199) and not at the `quantile` function below. There needs to be a `na.rm=T` to `range` as well. This is because if there are missing values in `corr_est` there will be missing in `range` and these will inevitably lead to missing values when assigning the `keep` variable below. Right now all chains with any missingness are thrown away, and I'm unsure if that's optimal

Comment (espenhgn) [reply scripts/pgs/LDpred2/fun.R:200]: Not sure either. 
Don't think it matters here, but perhaps best not to define a variable `range` replacing the `base::range` function within this function.

Comment (deepchocolate) [reply scripts/pgs/LDpred2/fun.R:200]: Yea, that's a good point, will change the name

Comment (deepchocolate) [reply scripts/pgs/LDpred2/fun.R:199]: `na.rm=T` in `range` causes other issues if an entire chain is missing, so will leave for now and address later.

File: scripts/pgs/LDpred2/calculateLD.R [hunk 2]
```diff
@@ -74,35 +84,38 @@ MAP <- obj.bigSNP$map
...
-cat('A total of', sum(useSNPs), 'will be used for LD calculation\n')
+nSNPs <- sum(useSNPs)
+if (nSNPs == 0) stop('No SNPs available.')
+cat('A total of', nSNPs, 'will be used for LD calculation\n')
 
 individualSample <- rows_along(G)
+# Extract individuals
+if (!is.na(extractIndividuals)) {
+  indIds <- filterFromFile(obj.bigSNP$fam, extractIndividuals, colFilter='sample.ID')
+  cat('Extracting ', sum(indIds), ' individuals\n')
```
Comment (deepchocolate) [inline scripts/pgs/LDpred2/calculateLD.R:102]: This line throws an error as `indIds` is the same object type as `obj.bigSNP$fam`. `sum` should be changed to `nrow` and on line 103 `indIds` should have been `indIds$fam$sample.ID`. Will change name of `indIds` to something better.
This was not detected in the tests and as far as I can see this parameter does not have a test. Will add that.

**Comment by espenhgn** [comment]
Hi @deepchocolate; @ofrei and I discussed restructuring some of the documentation and figured it's good to merge this soon. Is it ready enough?

**Comment by deepchocolate** [comment]
> Hi @deepchocolate; @ofrei and I discussed restructuring some of the documentation and figured it's good to merge this soon. Is it ready enough?

Yes, I can merge it today. There's still issues with calculating your own LD as it causes optimization errors during scoring. But I will leave that for now. I've tested most other things on MoBa data now and that has worked fine.
